apiVersion: v2
name: nebula-operator
description: Nebula Operator Helm chart for Kubernetes
version: 0.8.0
appVersion: 0.8.0
home: https://nebula-graph.io
sources:
- https://github.com/vesoft-inc/nebula-operator
keywords:
  - kubernetes
  - operator
  - nebula-graph
  - database
  - graph database
maintainers:
  - name: Vee Zhang
    email: vee.zhang@vesoft.com
  - name: Kevin Qiao
    email: kevin.qiao@vesoft.com
